const EnergyGenerated = require('../models/EnergyGenerated');

// Get all energy generated by month (mm-yyyy)
exports.getAllEnergyGeneratedByMonth = async (req, res) => {
  try {
    const records = await EnergyGenerated.findAll({
      order: [['month', 'ASC']]
    });
    res.json(records);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};