import { useReportContext } from '../context/ReportContext';
import { useState, useEffect } from 'react';
import * as reportApi from '../api/reportApi';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';

ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend);

const monthNames = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
];

const EnergyGeneratedChart = () => {
  const { energyGenerated, loading, error } = useReportContext();

  // ML insight state
  const [mlInsight, setMlInsight] = useState(null);
  const [mlLoading, setMlLoading] = useState(false);
  const [mlError, setMlError] = useState(null);

  useEffect(() => {
    setMlLoading(true);
    setMlError(null);
    reportApi.fetchEnergyGeneratedTrend()
      .then(data => setMlInsight(data.statement))
      .catch(err => setMlError('Failed to load Predictive Analytics'))
      .finally(() => setMlLoading(false));
  }, []);

  // Group data by year
  const yearMap = {};
  energyGenerated.forEach((d) => {
    const [mm, yyyy] = d.month.split('-');
    if (!yearMap[yyyy]) yearMap[yyyy] = Array(12).fill(null);
    yearMap[yyyy][parseInt(mm, 10) - 1] = d.solarEnergy;
  });

  const datasets = Object.keys(yearMap).sort().map((year, idx) => ({
    label: year,
    data: yearMap[year],
    backgroundColor: `hsl(${270 + idx * 60}, 70%, 60%)`,
  }));

  const chartData = {
    labels: monthNames,
    datasets,
  };

  const chartOptions = {
    responsive: true,
    plugins: {
      legend: { display: true },
      title: { display: true, text: 'Solar Energy Generated by Month (Segmented by Year)' },
    },
    scales: {
      x: {
        stacked: false,
      },
      y: {
        beginAtZero: true,
        stacked: false,
        title: {
          display: true,
          text: 'kWh',
        },
      },
    },
  };

  return (
    <div style={{ maxWidth: 700, margin: '0 auto' }}>
      {/* Chart section */}
      {loading ? (
        <p>Loading chart...</p>
      ) : error ? (
        <p style={{ color: 'red' }}>{error}</p>
      ) : (
        <Bar data={chartData} options={chartOptions} />
      )}
      {/* Predictive Analytics Subsection */}
      <div style={{
        margin: '24px 0 0 0',
        background: 'linear-gradient(90deg, #fffde7 60%, #ffe082 100%)',
        borderRadius: 14,
        padding: '1.2rem 2rem',
        boxShadow: '0 4px 16px rgba(255,193,7,0.15)',
        border: '2px solid #ffe082',
        width: '100%',
        maxWidth: 'none',
        display: 'flex',
        alignItems: 'center',
        gap: '1.1rem',
      }}>
        <span style={{
          fontWeight: 700,
          fontSize: '1.08rem',
          color: '#b28704',
          letterSpacing: '0.01em',
          marginRight: 16,
          display: 'flex',
          alignItems: 'center',
        }}>
          {/* Predictive Analytics Icon: Full Robot with Body */}
          <svg width="48" height="48" viewBox="0 0 48 48" fill="none" style={{marginRight:16}} xmlns="http://www.w3.org/2000/svg">
            <rect x="16" y="8" width="16" height="10" rx="4" fill="#fff" stroke="#222" strokeWidth="2"/>
            <circle cx="20" cy="13" r="1.5" fill="#222"/>
            <circle cx="28" cy="13" r="1.5" fill="#222"/>
            <rect x="23" y="4" width="2" height="6" rx="1" fill="#222"/>
            <circle cx="24" cy="4" r="1.2" fill="#222"/>
            <rect x="14" y="18" width="20" height="14" rx="6" fill="#fff" stroke="#222" strokeWidth="2.5"/>
            <rect x="8" y="22" width="4" height="10" rx="2" fill="#444"/>
            <rect x="36" y="22" width="4" height="10" rx="2" fill="#444"/>
            <rect x="18" y="34" width="3" height="7" rx="1.2" fill="#222"/>
            <rect x="27" y="34" width="3" height="7" rx="1.2" fill="#222"/>
            <rect x="21" y="23" width="6" height="5" rx="2" fill="#eee" stroke="#222" strokeWidth="1"/>
            <circle cx="24" cy="25.5" r="0.7" fill="#222"/>
            <circle cx="23" cy="27" r="0.5" fill="#bdbdbd"/>
            <circle cx="25" cy="27" r="0.5" fill="#bdbdbd"/>
          </svg>
          Predictive Analytics
        </span>
        <span style={{
          fontWeight: 500,
          fontSize: '1.08rem',
          color: '#b28704',
          fontFamily: 'Fira Mono, monospace',
          background: 'linear-gradient(90deg, #fffde7 60%, #ffe082 100%)',
          borderRadius: 6,
          padding: '0.5rem 1rem',
          boxShadow: '0 1px 4px rgba(255,193,7,0.10)',
        }}>
          {mlLoading ? 'Loading insight...' : mlError ? mlError : mlInsight}
        </span>
      </div>
    </div>
  );
};

export default EnergyGeneratedChart;
