const express = require('express');
const router = express.Router();
const energyGeneratedController = require('../controllers/energyGeneratedController');

// Get all energy generated by month (mm-yyyy)
router.get('/', energyGeneratedController.getAllEnergyGeneratedByMonth);

module.exports = router;